### ISSUE TITLE
[Feature req.] Generating a readable index file (HTML, Markdown...) to browse/navigate content

### ISSUE THREAD

**Issue by dotmick** [patrickkfkan/patreon-dl#16]
Hi!

Thanks again for the hard work in patreon-dl. I've been using it recently and it works great!

I'd like to suggest a feature if possible.

While the content is well downloaded and placed into the respective folders, it's not easy or a great experience to browse and access it quickly. I was wondering if patreon-dl could have an option that generates a readable index file (format could be HTML or Markdown, not sure what's easier/best/more scalable) at the root of each patreon directory?

That's it! Please le me know your thoughts, thanks!

**Comment by develroo** [comment]
Might be better to make it a separate tool rather than part of patreon-dl. Because of the logical layouot of `patreon-id/posts/id-postname/` It should be pretty simple to write python script to browse any particular patreon-id.


If I get time, I might make one myself. Though atm I have other things to deal with, so it is low priority for me.

**Comment by dotmick** [comment]
I wrote a quick-and-dirty/hacky python script that could be a starting point:

`import os
import json
import argparse
from datetime import datetime

def generate_index(directory):
    # HTML template for the index file
    html_template = """
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Patreon Content Index</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">
        <style>
            body {{
                font-family: "Open Sans", sans-serif;
                font-optical-sizing: auto;
                font-weight: 400;
                font-style: normal;
                margin: 0;
                padding: 0;
                background-color: #121212;
                color: #e0e0e0;
            }}
            a:hover {{
                color: #d3a8f1;
            }}
            a {{
                color: white;
                text-decoration: none;
                font-weight: bold;
            }}
            .container {{
                width: 90%;
                margin: 20px auto;
                display: grid;
                grid-template-columns: repeat(3, 1fr);
                gap: 40px;
            }}
            @media (max-width: 1200px) {{
                .container {{
                    grid-template-columns: repeat(2, 1fr);
                }}
            }}
            @media (max-width: 800px) {{
                .container {{
                    grid-template-columns: 1fr;
                }}
            }}
            .card {{
                background-color: #1e1e1e;
                box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
                border-radius: 8px;
                overflow: hidden;
                display: flex;
                flex-direction: column;
                justify-content: space-between;
            }}
            .card-header {{
                position: relative;
                height: 20rem;
                background-size: cover;
                background-position: center;
            }}
            .card-title {{
                padding: 10px;
                border-radius: 5px;
                margin-top: 10px;
                margin-left: 10px;
                margin-right: 10px;
                display: flex;
                flex-direction: column;
                align-items: flex-start;
            }}
            .card-title h2 {{
                margin: 0;
                font-size: 1.5em;
            }}
            .card-title .date {{
                font-size: 0.9em;
                margin-top: 5px;
            }}
            .card-content {{
                padding: 20px;
                flex-grow: 1;
            }}
            .card-content p {{
                color: #b0b0b0;
                line-height: 1.6;
                margin: 0;
            }}
            .card-content .no-content {{
                font-style: italic;
                color: #777;
            }}
            .card-footer {{
                padding: 10px;
                background-color: #282828;
                display: flex;
                align-items: center;
            }}
            .card-footer .path {{
                font-size: 0.9em;
                color: #999;
                word-break: break-all;
                margin-left: 5px;
            }}
            .video-player {{
                width: 100%;
                aspect-ratio: 16 / 9;
                margin-top: 20px;
            }}
            .folder-icon {{
                width: 20px;
                height: 20px;
                margin-right: 5px;
                fill: #999;
            }}
            .attachment-icon {{
                width: 16px;
                height: 16px;
                margin-right: 5px;
                fill: #999;
            }}
            .attachments {{
                margin-top: 10px;
            }}
            .attachment {{
                display: flex;
                align-items: center;
                margin-bottom: 5px;
            }}
            .attachment svg {{
                margin-right: 10px;
            }}
        </style>
    </head>
    <body>
        <div class="container">
            {content}
        </div>
    </body>
    </html>
    """

    # Initialize content
    content_list = []

    # Scan the downloaded Patreon directory
    posts_dir = os.path.join(directory, 'posts')
    for post_dir in os.listdir(posts_dir):
        post_path = os.path.join(posts_dir, post_dir)
        if os.path.isdir(post_path):
            post_info_path = os.path.join(post_path, 'post_info')
            embed_path = os.path.join(post_path, 'embed')
            attachments_path = os.path.join(post_path, 'attachments')
            if os.path.exists(post_info_path):
                # Read info.txt
                info_txt_path = os.path.join(post_info_path, 'info.txt')
                with open(info_txt_path, 'r') as info_file:
                    info_txt = info_file.read()

                # Read post-api.json
                post_json_path = os.path.join(post_info_path, 'post-api.json')
                with open(post_json_path, 'r') as json_file:
                    post_json = json_file.read()
                
                post_data = json.loads(post_json).get('data', {})
                attributes = post_data.get('attributes', {})

                # Get post title, content, and publish date
                post_title = attributes.get('title', 'No Title')
                post_content = attributes.get('content', '<p class="no-content">(content not available)</p>')
                post_date = attributes.get('published_at', 'Unknown Date')

                # Format date to human-readable format
                if post_date != 'Unknown Date':
                    post_date_obj = datetime.strptime(post_date, '%Y-%m-%dT%H:%M:%S.%f%z')
                    post_date_str = post_date_obj.strftime('%B %d, %Y')
                else:
                    post_date_obj = None
                    post_date_str = 'Unknown Date'

                # Get the first image for the header background
                banner_image = None
                for file in os.listdir(post_info_path):
                    if file.lower().endswith(('.png', '.jpg', '.jpeg', '.gif', '.webp')):
                        banner_image = os.path.join('posts', post_dir, 'post_info', file)
                        break

                # Check for video in the embed folder
                local_video = None
                if os.path.exists(embed_path):
                    for file in os.listdir(embed_path):
                        if file.lower().endswith(('.mp4', '.webm')):
                            local_video = os.path.join('posts', post_dir, 'embed', file)
                            break
                
                # Check for video URL
                video_url = None
                if attributes.get('embed'):
                    video_url = attributes.get('embed').get('url', None)
                    if video_url and 'youtu.be' in video_url:
                        video_url = video_url.replace('youtu.be/', 'www.youtube.com/embed/')
                    elif video_url and 'youtube' in video_url:
                        video_url = video_url.replace('watch?v=', 'embed/')
                    elif video_url and 'vimeo.com' in video_url:
                        parts = video_url.split('/')
                        if len(parts) > 4:
                            video_id = parts[-2]
                            video_hash = parts[-1]
                        else:
                            video_id = parts[-1]
                            video_hash = None

                        video_url = f'https://player.vimeo.com/video/{video_id}'
                        if video_hash:
                            video_url += f'?h={video_hash}'

                # Generate post content
                post_content_html = f'<div class="card">'

                # Add header with background image
                if banner_image:
                    post_content_html += f'<div class="card-header" style="background-image: url(\'{banner_image}\');"></div>'
                else:
                    post_content_html += f'<div class="card-header" style="background-color: #333;"></div>'

                # Add title and date
                post_content_html += f'<div class="card-title"><h2>{post_title}</h2>'
                post_content_html += f'<div class="date">{post_date_str}</div></div>'

                # Add post content
                post_content_html += f'<div class="card-content">'
                post_content_html += post_content

                # Add video player if available
                if local_video:
                    post_content_html += f'<div class="video-player-container"><video class="video-player" controls><source src="{local_video}" type="video/mp4">Your browser does not support the video tag.</video></div>'
                elif video_url:
                    post_content_html += f'<iframe class="video-player" src="{video_url}" title="Video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>'

                # Add attachments if available
                if os.path.exists(attachments_path) and os.listdir(attachments_path):
                    post_content_html += '<div class="attachments">'
                    for file in os.listdir(attachments_path):
                        attachment_path = os.path.join('posts', post_dir, 'attachments', file)
                        post_content_html += f'<div class="attachment"><svg width="19" height="25" viewBox="0 0 19 25" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M10.5149 0.408081H4.3125C2.10336 0.408081 0.3125 2.19894 0.3125 4.40808V20.4081C0.3125 22.6172 2.10336 24.4081 4.3125 24.4081H14.3125C16.5216 24.4081 18.3125 22.6172 18.3125 20.4081V6.59669L10.5149 0.408081Z" fill="#D9D9D9"/></svg><a href="{attachment_path}">{file}</a></div>'
                    post_content_html += '</div>'

                post_content_html += '</div>'

                # Add footer with local folder path
                post_content_html += f'<div class="card-footer">'
                post_content_html += f'<svg class="folder-icon" viewBox="0 0 24 24"><path d="M10 4H2C0.9 4 0 4.9 0 6V18C0 19.1 0.9 20 2 20H22C23.1 20 24 19.1 24 18V8C24 6.9 23.1 6 22 6H12L10 4Z" /></svg>'
                post_content_html += f'<div class="path">{post_dir}</div>'
                post_content_html += '</div>'

                post_content_html += '</div>'

                content_list.append((post_date_obj, post_content_html))

    # Sort posts by date, most recent first
    content_list.sort(key=lambda x: x[0] or datetime.min, reverse=True)

    # Combine sorted content
    content = ''.join([html for _, html in content_list])

    # Ensure the output directory exists
    output_path = os.path.join(directory, 'index.html')
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    # Write the HTML file
    with open(output_path, 'w') as file:
        file.write(html_template.format(content=content))

if __name__ == "__main__":
    # Parse command line arguments
    parser = argparse.ArgumentParser(description='Generate an HTML index file for Patreon content.')
    parser.add_argument('directory', type=str, help='Path to the directory containing the downloaded content')

    args = parser.parse_args()

    # Generate the index file
    generate_index(args.directory)`

To run: `python generate_index.py folder`

It could be improved in many ways, but at least I have an index that makes the downloaded content browsable.

**Comment by develroo** [comment]
> I wrote a quick-and-dirty/hacky python script that could be a starting point:

Pretty cool for a first attempt. Just one obvious problem. You did not `import os`  

That being said. it does work, but not on all creators. Not sure why. So for example. 
```
generate_pateon_indx "elventower - Elven Tower"
Traceback (most recent call last):
  File "/home/rooster/bin/generate_pateon_indx", line 291, in <module>
    generate_index(args.directory)
  File "/home/rooster/bin/generate_pateon_indx", line 175, in generate_index
    attributes = post_data.get('attributes', {})
                 ^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get'

```

```

generate_pateon_indx "justinalexander - Justin Alexander"
Traceback (most recent call last):
  File "/usr/local/bin/generate_pateon_indx", line 291, in <module>
    generate_index(args.directory)
  File "/usr/local/bin/generate_pateon_indx", line 241, in generate_index
    post_content_html += post_content
TypeError: can only concatenate str (not "NoneType") to str
```

But something like Clickspring worked.

**Comment by deibeljc** [comment]
I wrote a little script to filter and convert posts to an epub

```python
import os
import re
from ebooklib import epub
from simple_term_menu import TerminalMenu


def select_folders():
    current_dir = os.getcwd()
    top_level_folders = [f for f in os.listdir(current_dir)]

    if not top_level_folders:
        print(f"Error: No folders found in {current_dir}")
        return None

    terminal_menu = TerminalMenu(
        top_level_folders,
        title="Select the top-level folder to process (ENTER to confirm):",
    )
    selected_index = terminal_menu.show()

    if selected_index is None:
        print("No folder selected. EPUB creation aborted.")
        return None

    selected_folder = top_level_folders[selected_index]
    posts_folder = os.path.join(current_dir, selected_folder, "posts")

    if not os.path.exists(posts_folder):
        print(
            f"Error: 'posts' folder not found in {os.path.join(current_dir, selected_folder)}"
        )
        return None

    return posts_folder


def create_epub_from_chapters():
    posts_folder = select_folders()
    if not posts_folder:
        print("No folder selected. EPUB creation aborted.")
        return

    # Add title input
    title = input("Enter the title for the EPUB: ").strip()
    if not title:
        print("No title entered. EPUB creation aborted.")
        return

    # Generate identifier from title
    identifier = title.lower().replace(" ", "_")

    # Add filter input
    filter_input = input(
        "Enter a filter for folder names (leave empty for no filter): "
    ).strip()

    print(f"Starting to process folders in {posts_folder}")

    book = epub.EpubBook()
    book.set_identifier(identifier)
    book.set_title(title)
    book.set_language("en")

    chapters = []
    processed_folders = 0
    successful_extractions = 0

    for folder_name in os.listdir(posts_folder):
        # Apply filter
        if filter_input and filter_input.lower() not in folder_name.lower():
            continue

        folder_path = os.path.join(posts_folder, folder_name)
        if not os.path.isdir(folder_path):
            continue

        processed_folders += 1
        print(f"\nProcessing folder: {folder_name}")

        info_file_path = os.path.join(folder_path, "post_info", "info.txt")

        if not os.path.exists(info_file_path):
            print(f"  Error: info.txt not found in {folder_path}")
            continue

        try:
            with open(info_file_path, "r", encoding="utf-8") as info_file:
                info_content = info_file.read()

            # Extract title
            title_match = re.search(r"Title: (.+)", info_content)
            if not title_match:
                print(f"  Error: Title not found in {info_file_path}")
                continue
            title = title_match.group(1)
            print(f"  Title found: {title}")

            # Extract chapter number
            chapter_match = re.search(r"Chapter (\d+\.\d+)", title)
            if not chapter_match:
                print(f"  Error: Chapter number not found in title: {title}")
                continue
            chapter_number = chapter_match.group(1)
            print(f"  Chapter number: {chapter_number}")

            # Extract content
            content_match = re.search(r"Content: (.+)", info_content, re.DOTALL)
            if not content_match:
                print(f"  Error: Content not found in {info_file_path}")
                continue
            content = content_match.group(1)
            print(f"  Content extracted (length: {len(content)} characters)")

            # Create chapter
            chapter = epub.EpubHtml(
                title=title, file_name=f"chapter_{chapter_number}.xhtml", lang="en"
            )
            chapter.content = f"<h1>{title}</h1>\n{content}"

            book.add_item(chapter)
            chapters.append(chapter)
            successful_extractions += 1
            print(f"  Successfully added chapter to the book")

        except Exception as e:
            print(f"  Error processing {info_file_path}: {str(e)}")

    print(f"\nProcessed {processed_folders} folders")
    print(f"Successfully extracted {successful_extractions} chapters")

    if not chapters:
        print("No chapters were successfully extracted. EPUB creation aborted.")
        return

    # Sort chapters from smallest to largest based on chapter number
    chapters.sort(
        key=lambda x: tuple(
            map(int, re.search(r"Chapter (\d+)\.(\d+)", x.title).groups())
        )
    )

    # Add chapters to the book
    book.toc = tuple(chapters)

    # Add chapters to the spine
    book.spine = chapters

    book.add_item(epub.EpubNcx())
    book.add_item(epub.EpubNav())

    # Define CSS
    style = "BODY {color: white;}"
    nav_css = epub.EpubItem(
        uid="style_nav", file_name="style/nav.css", media_type="text/css", content=style
    )
    book.add_item(nav_css)

    # Write to file
    try:
        epub_filename = f"{identifier}.epub"

        epub.write_epub(epub_filename, book, {})
        print(f"\nEPUB file '{epub_filename}' created successfully with title: {title}")
    except Exception as e:
        print(f"\nError creating EPUB file: {str(e)}")


# Usage
if __name__ == "__main__":
    create_epub_from_chapters()

```

**Comment by patrickkfkan** [comment]
Updated v3.0.0, which supports browsing downloaded content through integrated web server. Unfortunately, downloads made with previous versions are not browseable, so you would have to re-download -- but `patreon-dl` will, by default, skip media files that already exist by filename, so hopefully the process won't take too long.
